# Generated by Django 2.0 on 2017-12-30 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('bio', models.TextField(max_length=512)),
                ('avatar', models.ImageField(default='No Image', upload_to='')),
            ],
        ),
    ]
